### ISSUE TITLE
ALC256_v2 Headphone microphone does not work

### ISSUE THREAD

**Issue by yakimka** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#3]
I have Dell 7577 laptop with combo jack and Intel 7300HQ processor.
After installing CloverHDA by instructions audio works well except headphone microphone

**Comment by yakimka** [comment]
[CodecDump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2364433/CodecDump.zip)

**Comment by insanelydeepak** [comment]
Hi 
sure i will look and report back

**Comment by insanelydeepak** [comment]
Hi 
are you using codeccommander and SSDT256 ?

**Comment by yakimka** [comment]
Yes, codeccommander and SSDT-ALC256.aml

**Comment by insanelydeepak** [comment]
OSX Version ??

**Comment by yakimka** [comment]
10.13.6

**Comment by Andrw0830** [comment]
"dmesg | grep hda
[    2.486987] snd_hda_intel 0000:00:1f.3: enabling device (0000 -> 0002)
[    3.337016] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    3.416717] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC3246: line_outs=2 (0x14/0x1b/0x0/0x0/0x0) type:speaker
[    3.416720] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    3.416721] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[    3.416722] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[    3.416723] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[    3.416725] snd_hda_codec_realtek hdaudioC0D0:      Headset Mic=0x19
[    3.416726] snd_hda_codec_realtek hdaudioC0D0:      Headphone Mic=0x1a
[    3.416727] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12"

Wanted to help you out since I have the same codec and same Headset Mic Issue. In Ubuntu though, with my headset plugged in I get 2 devices 'Headset Microphone - Built-in Audio' and 'Microphone - Built-in Audio' in Sound options. The headset mic actually shows it recording sound when the plain Microphone one is selected. So from this, it appears 0x1a is probably the pinout. Not sure if that would be change for different headsets.

**Comment by insanelydeepak** [comment]
Hi 
guys due to lack of time and festive season i didnt look up on this issue ,

are you available to fix this ? 
if yes feel free to re-open issue
